# Generated by Django 5.0.6 on 2024-05-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
